### ISSUE TITLE
RTF Image not converting

### ISSUE THREAD

**Issue by sathishkumarwinxp** [erdomke/RtfPipe#33]
I tried RTF document, it contains image with text. the html output not showing image.

I am using C# .NET

![imageIssue](https://user-images.githubusercontent.com/13523813/65307563-a96b9e80-dba5-11e9-9cf4-703cecae0325.png)

**Comment by erdomke** [comment]
If you could attach the actual RTF document, it would help with debugging. My hunch is that the RTF contains an image in a file format which browsers cannot render (e.g. *.emf or *.wmf). In order to get such an image to work, you would need to use a separate library to convert that image format to a web-compatible one (such as *.png, *.gif, *.jpg, etc.).

**Comment by sathishkumarwinxp** [comment]
Thanks for quick reply. This document contains WMF Image.

**Comment by sanjay95** [comment]
@sathishkumarwinxp @erdomke  could you guys help me in converting RTF to HTML which has image.
Need help in html setting, I am not sure what to give in setting 
var html = Rtf.ToHtml(source, new RtfHtmlSettings() { });

Without setting, converted html does not have image content or even image tag.

**Comment by erdomke** [comment]
@sanjay95 As noted, a lot of images cannot be converted automatically by the library as they are encoded with image formats that aren't compatible with the web. To help advise you with your problem, can you send an example RTF document that you are having issues converting? Thanks!

**Comment by erdomke** [comment]
From my tests, it does appear that the `*.wmf` image was being output to the HTML, it just would not render in a browser since it is not a format that browsers support. I made some tweaks to convert the format to `*.png` if you are using the library in a .Net Framework project (where `System.Drawing` is available). However, if you are using .Net Core (or just want control over how images are handled), pass in an instance of `RtfHtmlSettings` with an `ImageUriGetter` specified. In that callback, you can handle the image however you like. These updates are in the latest package on NuGet.

**Comment by goroggy** [comment]
Eric, I have the same issue. I convert PDF documents using Abbyy. The RTF has {\pict\jpegblip\picwgoal4416\pichgoal3091
so I assume this pic should be converted. 
RtfPipe nuget 1.0.7388.1242.
I attach the RTF. Please advise. Thanks gor.
[82020HU0000AD3309(02).zip](https://github.com/erdomke/RtfPipe/files/5039901/82020HU0000AD3309.02.zip)

**Comment by dunce** [comment]
Hi @erdomke,
Firstly, thanks for this awesome tool!
There is still an issue with some images where **ImageUriGetter** delegate doesn't even get called.
See the _sample1.rtf_ here: **[https://filesamples.com/formats/rtf](https://filesamples.com/formats/rtf)**
Thanks!

**Comment by evite09** [comment]
Does anyone have an example of how images work with RtfHtmlSettingscon.ImageUriGetter please?

**Comment by evite09** [comment]
> @sathishkumarwinxp @erdomke could you guys help me in converting RTF to HTML which has image.
> Need help in html setting, I am not sure what to give in setting
> var html = Rtf.ToHtml(source, new RtfHtmlSettings() { });
> 
> Without setting, converted html does not have image content or even image tag.

The same thing happens to me, any suggestions?

**Comment by erdomke** [comment]
If an image is part of a complex shape, it is possible that the library doesn't know how to handle it. The code in the library today is mostly focused on handling simple picture tags. I have updated [the documentation](https://github.com/erdomke/RtfPipe/wiki/Documentation#custom-image-conversion) with an example of how to use the callback in the settings with these simple picture tags.
