### ISSUE TITLE
ToText(...)

### ISSUE THREAD

**Issue by TonyValenti** [erdomke/RtfPipe#62]
Hi @erdomke -
Could you add a few overloads to RtfPipe?
```
Rtf.ToHtml(string RtfContent);
Rtf.ToText(string RtfContent);
```

I'm particularly interested in the ```ToText``` method that will convert RTF to plain text instead.  If we need to contribute a donation to enable this, please:
1.  Let us know how much (just post it here)
2. An online link we can use to make the donation
3. An ETA on when a new build with the new method will exist.

Thanks!

**Comment by erdomke** [comment]
Actually, you can already do this today if you are willing to add a dependency on one of my other libraries, [BracketPipe](https://github.com/erdomke/BracketPipe). As [described on StackOverflow](https://stackoverflow.com/questions/46119392/how-do-i-convert-an-rtf-string-to-a-markdown-string-and-back-c-net-core-or/54755138#54755138), you could use either the [MarkdownWriter](https://github.com/erdomke/BracketPipe/blob/master/src/BracketPipe/Parser/Text/MarkdownWriter.cs) or [PlainTextWriter](https://github.com/erdomke/BracketPipe/blob/master/src/BracketPipe/Parser/Text/PlainTextWriter.cs) classes to write out either Markdown or plain text instead. If that doesn't work for you, those two classes give you a good idea of how you could create your own class inheriting from [XmlWriter](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmlwriter?view=net-5.0) in order to pull out just the text content. If that still doesn't meet your need, let me know.

```cs
using BracketPipe;
using RtfPipe;

private string RtfToMarkdown(string source)
{
  using (var w = new System.IO.StringWriter())
  using (var md = new MarkdownWriter(w))
  {
    Rtf.ToHtml(source, md);
    md.Flush();
    return w.ToString();
  }
}
```

**Comment by JanRajnoha** [comment]
Hi @erdomke , I don't know, if this repo is still supported, but I tried your sample and it is not working. Wen I try run it, it crash with "Stack empty" exception. 

How could I convert rtf to plain text?
